### ISSUE TITLE
ClinVar GRCh37 links missing variant id in URL

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#1097]
(requires modification to toml file for vcfanno in iobio gru backend)

**Comment by tonydisera** [comment]
This missing clinvar uid is due to a missing field in the vcfanno toml file for ClinVar (GRCh37 only):

I mistakenly missed including the ID vcfanno field for ClinVar GRCh37.  (It is correctly included for ClinVar GRCh38 vcfanno).
 
The ID field (bold) needs to be added to data/annotations/GRCh37/vcfanno_annotate_variants.toml:
 
fields=["CLNDN", "CLNSIG","ALLELEID","CLNREVSTAT",**"ID"**]
names=["CLNDN", "CLNSIG","ALLELEID","CLNREVSTAT",**"CLNUID"**]
ops=["self", "self", "self", "self",**"self"**]

**Comment by anderspitman** [comment]
I can add it in. It will require a new data directory version, but only a small change since we're using hard links. Deployment is still a bit of a pain though. How time sensitive is this?

**Comment by tonydisera** [comment]
Thanks @anderspitman. This isn't time critical. If we can get this fixed in the next few weeks, that will be great.

**Comment by anderspitman** [comment]
@tonydisera this is what I'm seeing for the current file:

```toml
[[annotation]]
file="/iobio-gru-backend/static/clinvar/GRCh37/clinvar.vcf.gz"
fields=["CLNDN", "CLNSIG", "CLNREVSTAT","ALLELEID","CLNREVSTAT"]
ops=["self", "self", "self", "self", "self"]
[[annotation]]
file="/gru_data/annotations/GRCh37/gnomad/gnomad.genomes.r2.1.1.sites.iobio.slim.vcf.gz"
fields=["AC", "AN", "AF", "AF_popmax", "nhomalt", "DP", "AF_fin", "AF_nfe", "AF_oth", "AF_amr", "AF_afr", "AF_asj", "AF_eas", "AF_sas"]
names=["gg2_1_1_AC", "gg2_1_1_AN", "gg2_1_1_AF", "gg2_1_1_AF_popmax", "gg2_1_1_nhomalt", "gg2_1_1_DP", "gg2_1_1_AF_fin", "gg2_1_1_AF_nfe", "gg2_1_1_AF_oth", "gg2_1_1_AF_amr", "gg2_1_1_AF_afr", "gg2_1_1_AF_asj", "gg2_1_1_AF_eas", "gg2_1_1_AF_sas"]
ops=["self", "self", "self", "self", "self", "self","self","self","self","self","self","self","self","self"]
[[annotation]]
file="/gru_data/annotations/GRCh37/gnomad/gnomad.exomes.r2.1.1.sites.vcf.gz"
fields=["AC", "AN", "AF", "AF_popmax", "nhomalt", "DP"]
names=["ge2_1_1_AC", "ge2_1_1_AN", "ge2_1_1_AF", "ge2_1_1_AF_popmax", "ge2_1_1_nhomalt", "ge2_1_1_DP"]
ops=["self", "self", "self", "self", "self", "self"]
```

I'm worried I might apply the changes you described above incorrectly. Can you provide the exact file you want me to replace this with?
